---
AWSTemplateFormatVersion: 2010-09-09

Description: AWS Google Translator ELB and subroutines

Parameters:
  Project:
    Description: Project Name Tag
    Type: String
    Default: AWSGT

Resources:
 SGELBAWSGT:
   Type: AWS::EC2::SecurityGroup
   Properties:
    GroupDescription: "AWS Google Translator Load Balancer Security Group"
    VpcId:
      Fn::ImportValue: "AWSGT-VPC"
    SecurityGroupEgress:
      CidrIp: 0.0.0.0/0
      IpProtocol: -1
    SecurityGroupIngress:
    - IpProtocol: TCP
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0
    - IpProtocol: TCP
      FromPort: 443
      ToPort: 443
      CidrIp: 0.0.0.0/0
    - IpProtocol: ICMP
      FromPort: -1
      ToPort: -1
      CidrIp: 0.0.0.0/0
    Tags:
    - Key: Name
      Value: AWS GT ELB security group
    - Key: Project
      Value: !Ref Project

 ELBAWSGTToNodesSG:
  Type: AWS::EC2::SecurityGroup
  Properties:
   GroupDescription: "Security group for communication between AWS GT ELB and nodes"
   VpcId:
      Fn::ImportValue: "AWSGT-VPC"
   SecurityGroupEgress:
    CidrIp: 0.0.0.0/0
    IpProtocol: -1
   SecurityGroupIngress:
   - SourceSecurityGroupId: !Ref SGELBAWSGT
     IpProtocol: TCP
     FromPort: 8080
     ToPort: 8080
   Tags:
   - Key: Name
     Value: AWS GT ELB security group
   - Key: Project
     Value: !Ref Project

 ELBAWSGT:
  Type: AWS::ElasticLoadBalancing::LoadBalancer
  Properties:
    Tags:
    - Key: Name
      Value: AWS GT ELB security group
    - Key: Project
      Value: !Ref Project
    LoadBalancerName: "aws-gt-elb"
    SecurityGroups:
      - !Ref SGELBAWSGT
    Scheme: internet-facing
    Subnets: !Ref Subnets
    Listeners:
    - LoadBalancerPort: 80
      InstancePort: 8080
      Protocol: HTTP
    - LoadBalancerPort: 443
      InstancePort: 8080
      Protocol: HTTPS
      InstanceProtocol: HTTP

