---
- name: Install add-apt-repostory
  become: true
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  become: true
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  become: true
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: true
  apt: name={{item}} state=latest update_cache=yes force=yes
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Install JCE local_policy.jar
  become: true
  copy:
    src: "local_policy.jar"
    dest: "{{ java_dir }}/jre/lib/security/local_policy.jar"

- name: Install JCE US_export_policy.jar
  become: true
  copy:
    src: "US_export_policy.jar"
    dest: "{{ java_dir }}/jre/lib/security/US_export_policy.jar"