server:
  port: 8090
  address: 127.0.0.1

logging.level:
  io.swagger.models.parameters.AbstractSerializableParameter: ERROR

info.app.name:
  AWS Google Translator
info.app.description:
  This is a simple RESTful microservice which translates text using Google Translate API
info.app.version:
  @project.version@