server:
  port: 8090
  address: 127.0.0.1

logging.level:
  io.swagger.models.parameters.AbstractSerializableParameter: ERROR

info.app.name:
  Spring Sample Application
info.app.description:
  This is my first spring boot application
info.app.version:
  0.0.1-SNAPSHOT