---
AWSTemplateFormatVersion: 2010-09-09

Description: AWS Google Translator Auto Scaling Group and subroutines

Parameters:
  Project:
    Description: Project Name Tag
    Type: String
    Default: AWSGT

  ImageId:
    Description: AMI id
    Type: String

  InstanceType:
    Description: ec2 instance type
    Type: String
    AllowedValues:
     - t2.micro
     - t2.medium
    ConstraintDescription: must be a valid EC2 instance type.
    Default: t2.micro


Resources:
  NodeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "aws-gt-ec2-node-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        -
          Effect: Allow
          Principal:
            Service:
              - ec2.amazonaws.com
          Action:
            - sts:AssumeRole

  NodeProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref NodeRole

  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      BlockDeviceMappings:
      - DeviceName: "/dev/sdb"
        Ebs:
          VolumeSize: '10'
          VolumeType: 'gp2'
      SecurityGroups:
      - Fn::ImportValue:
          !Sub "AWSGT-ELB-EC2-SecurityGroup"
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref NodeProfile
      Metadata:
        AWS::CloudFormation::Init:
          config:
            commands:
              01_apt_update:
                command: 'apt-get update'


