#!groovy

//noinspection GroovyAssignabilityCheck
pipeline {

    agent any

    stages {
        stage('Clean working directory and Checkout') {
            steps {
                deleteDir()
                checkout scm
            }
        }

        stage('Validate parameters') {
            steps {
                script {
                    if (params.AWS_ACCOUNT == null || params.AWS_ACCOUNT == "") {
                        error("Can't proceed without AWS Account Id")
                    } else if (params.REGION == null || params.REGION == "") {
                        error("Can't proceed without REGION")
                    } else if (params.CF_ROLE == null || params.CF_ROLE == "") {
                        error("Can't proceed without CloudFormation IAM role")
                    } else if (params.JENKINS_ROLE == null || params.JENKINS_ROLE == "") {
                        error("Can't proceed without Jenkins IAM role")
                    }
                }
            }
        }

        stage('Build') {
            steps {
                sh "mvn clean install -DuseCommitHash -DskipTests -T 1C"
            }
        }

        stage("Unit tests") {
            steps {
                sh "mvn test -Dmaven.test.failure.ignore=true -T 1C"
            }
        }

        stage('Set required environment variables') {
            steps {
                script {

                    env.VPC_PARAMS_PATH = "cd/cloudformation/vpc/${REGION}/vpc_params.yaml"
                    env.S3_PARAMS_PATH = "cd/cloudformation/s3/${REGION}/s3_params.yaml"
                    env.ELB_PARAMS_PATH = "cd/cloudformation/elb/${REGION}/elb_params.yaml"
                    env.ASG_PARAMS_PATH = "cd/cloudformation/asg/${REGION}/asg_params.yaml"

                    env.VPC_TEMPLATE_PATH = "cd/cloudformation/vpc/vpc_cfn.yaml"
                    env.S3_TEMPLATE_PATH = "cd/cloudformation/s3/s3_cfn.yaml"
                    env.ELB_TEMPLATE_PATH = "cd/cloudformation/elb/elb_cfn.yaml"
                    env.ASG_TEMPLATE_PATH = "cd/cloudformation/asg/asg_cfn.yaml"

                    env.VPC_STACK_NAME = "aws-gt-vpc"
                    env.S3_STACK_NAME = "aws-gt-s3"
                    env.ELB_STACK_NAME = "aws-gt-elb"

                    env.AWS_PARTITION = "aws"
                    env.CF_ROLE = "arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT}:role/${CF_ROLE}"
                }
            }
        }

        stage('Create VPC CloudFormation') {
            steps {
                script {
                    //noinspection GroovyAssignabilityCheck
                    withAWS(role: "${JENKINS_ROLE}", roleAccount: "${AWS_ACCOUNT}", region: "${REGION}") {
                        VPC_STACK_NAME = sh returnStdout: true, script: "aws cloudformation describe-stacks --output json | jq -r '.Stacks[].StackName' | grep \"$VPC_STACK_NAME\" | tr -d '\040\011\012\015'"
                        if (VPC_STACK_NAME == null || VPC_STACK_NAME == '') {
                            cfnValidate(file: "${VPC_TEMPLATE_PATH}")
                            cfnUpdate(stack: "${VPC_STACK_NAME}", file: "${VPC_TEMPLATE_PATH}", paramsFile: "${VPC_PARAMS_PATH}", roleArn: "${CF_ROLE}", tags: ["Name=$VPC_STACK_NAME", "Project=AWSGT"])
                        }
                    }
                }
            }
        }

        stage('Create S3 CloudFormation') {
            steps {
                script {
                    //noinspection GroovyAssignabilityCheck
                    withAWS(role: "${JENKINS_ROLE}", roleAccount: "${AWS_ACCOUNT}", region: "${REGION}") {
                        S3_STACK_NAME = sh returnStdout: true, script: "aws cloudformation describe-stacks --output json | jq -r '.Stacks[].StackName' | grep \"$S3_STACK_NAME\" | tr -d '\040\011\012\015'"
                        if (S3_STACK_NAME == null || S3_STACK_NAME == '') {
                            cfnValidate(file: "${S3_TEMPLATE_PATH}")
                            cfnUpdate(stack: "${S3_STACK_NAME}", file: "${S3_TEMPLATE_PATH}", paramsFile: "${S3_PARAMS_PATH}", roleArn: "${CF_ROLE}", tags: ["Name=$S3_STACK_NAME", "Project=AWSGT"])
                        }
                    }
                }
            }
        }

        stage('Create ELB CloudFormation') {
            steps {
                script {
                    //noinspection GroovyAssignabilityCheck
                    withAWS(role: "${JENKINS_ROLE}", roleAccount: "${AWS_ACCOUNT}", region: "${REGION}") {
                        ELB_STACK_NAME = sh returnStdout: true, script: "aws cloudformation describe-stacks --output json | jq -r '.Stacks[].StackName' | grep \"$ELB_STACK_NAME\" | tr -d '\040\011\012\015'"
                        if (ELB_STACK_NAME == null || ELB_STACK_NAME == '') {
                            cfnValidate(file: "${ELB_TEMPLATE_PATH}")
                            cfnUpdate(stack: "${ELB_STACK_NAME}", file: "${ELB_TEMPLATE_PATH}", paramsFile: "${ELB_PARAMS_PATH}", roleArn: "${CF_ROLE}", tags: ["Name=$ELB_STACK_NAME", "Project=AWSGT"])
                        }
                    }
                }
            }
        }

        stage('Build AMI') {
            steps {
                //noinspection GroovyAssignabilityCheck
                withAWS(role: "${JENKINS_ROLE}", roleAccount: "${AWS_ACCOUNT}", region: "${REGION}") {
                    dir('cd/packer') {
                        script {
                            VPC_ID = sh returnStdout: true, script: "aws ec2 describe-vpcs --output json --filters Name=tag:Project,Values=AWSGT | jq -r .Vpcs[0].VpcId | tr -d '\040\011\012\015'"
                            SUBNET_ID = sh returnStdout: true, script: "aws ec2 describe-subnets --filters Name=vpc-id,Values=${VPC_ID} --output json | jq -r .Subnets[0].SubnetId | tr -d '\040\011\012\015'"

                            sh "packer build -color=false -machine-readable -only=awsgt-ami -var 'vpc_id=${VPC_ID}' -var 'subnet_id=${SUBNET_ID}' awsgt-ami.json | tee build.log"
                            env.AMI_ID = sh returnStdout: true, script: "cat packer-manifest.json | jq -r '.builds[] | select (.name==awsgt-ami) | .artifact_id'"
                            if (env.AMI_ID == null || env.AMI_ID == "") {
                                error("AMI ID empty, build failed")
                            }
                        }
                        echo "Created new AMI: ${AMI_ID}"
                    }
                }
            }
        }


    }

    post {
        always {
            junit '**/target/surefire-reports/*.xml'
            junit '**/target/failsafe-reports/*.xml'
        }
        success {
            script {
                currentBuild.result = 'SUCCESS'
            }
        }
        failure {
            script {
                currentBuild.result = 'FAILURE'
            }
        }
        unstable {
            script {
                currentBuild.result = 'UNSTABLE'
            }
        }
    }
}