---
AWSTemplateFormatVersion: 2010-09-09

Description: AWS Google Translator ELB and subroutines

Parameters:
  Project:
    Description: Project Name Tag
    Type: String
    Default: AWSGT
  VPCStackName:
    Description: VPC STACK Name
    Type: String
  ELBAccountID:
    Description: Elastic Load Balancing Account ID
    Type: String

Resources:
 SGELBAWSGT:
   Type: AWS::EC2::SecurityGroup
   Properties:
    GroupDescription: "AWS Google Translator Load Balancer Security Group"
    VpcId:
      Fn::ImportValue:
        !Sub "${VPCStackName}-AWSGT-VPC"
    SecurityGroupEgress:
      CidrIp: 0.0.0.0/0
      IpProtocol: -1
    SecurityGroupIngress:
    - IpProtocol: TCP
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0
    - IpProtocol: TCP
      FromPort: 443
      ToPort: 443
      CidrIp: 0.0.0.0/0
    - IpProtocol: ICMP
      FromPort: -1
      ToPort: -1
      CidrIp: 0.0.0.0/0
    Tags:
    - Key: Name
      Value: AWS GT ELB security group
    - Key: Project
      Value: !Ref Project

 AccessLogBucket:
   Type: AWS::S3::Bucket
   DeletionPolicy: Delete
   Properties:
    BucketName: "aws-gt-elb-logs"
    LifecycleConfiguration:
      Rules:
        - Id: "DeleteLogsInAMonth"
          Status: Enabled
          ExpirationInDays: '30'
          NoncurrentVersionExpirationInDays: '30'
          AbortIncompleteMultipartUpload:
            DaysAfterInitiation: '1'
    Tags:
    - Key: Project
      Value: !Ref Project
    - Key: Type
      Value: "s3-aws-gt-elb-logs"

 AccessLogBucketPolicy:
   Type: AWS::S3::BucketPolicy
   Properties:
    Bucket: !Ref AccessLogBucket
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${ELBAccountID}:root"
          Action: 's3:PutObject'
          Resource:
          - !Join
            - ''
            - - "arn:aws:s3:::"
              - !Ref AccessLogBucket
              - "/*"
          - !Join
            - ''
            - - "arn:aws:s3:::"
              - !Ref AccessLogBucket
