---
AWSTemplateFormatVersion: 2010-09-09

Description: AWS Google Translator VPC

Parameters:
  Project:
    Description: Project Name Tag
    Type: String
    Default: AWSGT


Resources:
  AWSGTVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: AWS GT VPC
      - Key: Project
        Value: !Ref Project

  AWSGTPublicSubnet0:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AWSGTVPC
      CidrBlock: 10.0.0.0/26"
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: AWS GT Public Subnet 0
        - Key: Project
          Value: !Ref Project

  AWSGTPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AWSGTVPC
      CidrBlock: 10.0.64.0/26"
      AvailabilityZone: !Select
        - '1'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: AWS GT Public Subnet 1
        - Key: Project
          Value: !Ref Project

  AWSGTInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: AWS GT Internet Gateway
      - Key: Project
        Value: !Ref Project

  AWSGTAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref AWSGTVPC
      InternetGatewayId: !Ref AWSGTInternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AWSGTVPC
      Tags:
      - Key: Name
        Value: AWS GT Public Route Table
      - Key: Project
        Value: !Ref Project

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref AWSGTInternetGateway

  PublicSubnetRouteTableAssociation0:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AWSGTPublicSubnet0
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AWSGTPublicSubnet1
      RouteTableId: !Ref PublicRouteTable

Outputs:
  VPC:
    Description: AWS Google Translate VPC
    Value: !Ref AWSGTVPC
  AZ0:
    Description: Availability Zone 0
    Value: !GetAtt
      - AWSGTPublicSubnet0
      - AvailabilityZone
  AZ1:
    Description: Availability Zone 1
    Value: !GetAtt
      - AWSGTPublicSubnet1
      - AvailabilityZone

